# Production Deployment Configuration
apiVersion: v1
kind: Namespace
metadata:
  name: virtualfit-production

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: virtualfit-api
  namespace: virtualfit-production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: virtualfit-api
  template:
    metadata:
      labels:
        app: virtualfit-api
    spec:
      containers:
      - name: api
        image: virtualfit/backend:production
        ports:
        - containerPort: 8000
        env:
        - name: REDIS_URL
          value: "redis://redis-service:6379/0"
        - name: MONGO_URL
          value: "mongodb://mongo-service:27017"
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
  namespace: virtualfit-production
spec:
  replicas: 5
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      containers:
      - name: worker
        image: virtualfit/backend:production
        command: ["celery", "-A", "src.workers.celery_app", "worker", "--loglevel=info"]
        env:
        - name: REDIS_URL
          value: "redis://redis-service:6379/0"
        resources:
          requests:
            memory: "4Gi"
            cpu: "2000m"

---
apiVersion: v1
kind: Service
metadata:
  name: virtualfit-api-service
  namespace: virtualfit-production
spec:
  selector:
    app: virtualfit-api
  ports:
  - port: 80
    targetPort: 8000
  type: LoadBalancer